name: "xfg - Repo as Code"
description: "Sync files and manage settings across GitHub, Azure DevOps, and GitLab"
author: "Anthony Spruyt"

branding:
  icon: "git-merge"
  color: "blue"

inputs:
  command:
    description: "Command to run (sync or settings)"
    required: false
    default: "sync"
  config:
    description: "Path to YAML config file"
    required: true
  dry-run:
    description: "Preview mode - show what would change without creating PRs"
    required: false
    default: "false"
  work-dir:
    description: "Directory for cloning repositories"
    required: false
    default: "./tmp"
  retries:
    description: "Number of network retries"
    required: false
    default: "3"
  branch:
    description: "Override sync branch name"
    required: false
  merge:
    description: "PR merge mode (manual/auto/force/direct)"
    required: false
  merge-strategy:
    description: "Merge strategy (merge/squash/rebase)"
    required: false
  delete-branch:
    description: "Delete branch after merge"
    required: false
    default: "false"
  github-token:
    description: "GitHub token for authentication"
    required: false
    default: ${{ github.token }}
  azure-devops-token:
    description: "Azure DevOps Personal Access Token"
    required: false
  gitlab-token:
    description: "GitLab token for authentication"
    required: false
  github-app-id:
    description: "GitHub App ID (generates installation tokens automatically)"
    required: false
  github-app-private-key:
    description: "GitHub App private key (PEM format) for JWT signing"
    required: false
  no-delete:
    description: "Skip deletion of orphaned resources even if deleteOrphaned is configured"
    required: false
    default: "false"
  xfg-package:
    description: "Override xfg package to install (npm package name, local .tgz path, or 'skip' to use pre-installed). Defaults to the version matching this action release."
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: "24"

    - name: Install GitLab CLI
      if: ${{ inputs.gitlab-token != '' }}
      shell: bash
      run: |
        curl -sSL "https://raw.githubusercontent.com/upciti/wakemeops/main/assets/install_repository" | sudo bash
        sudo apt-get install -y glab

    - name: Install Azure DevOps CLI extension
      if: ${{ inputs.azure-devops-token != '' }}
      shell: bash
      run: az extension add --name azure-devops --yes

    - name: Configure git
      shell: bash
      env:
        AZURE_DEVOPS_TOKEN: ${{ inputs.azure-devops-token }}
        GITLAB_TOKEN: ${{ inputs.gitlab-token }}
      run: |
        # Configure git user (only if not already configured)
        if [ -z "$(git config --global user.name)" ]; then
          git config --global user.name "github-actions[bot]"
        fi
        if [ -z "$(git config --global user.email)" ]; then
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
        fi

        # Note: GitHub auth is handled by xfg via per-command -c url.insteadOf
        # No global URL rewrite needed for GitHub repos

        # Azure DevOps - inline credential helper
        if [ -n "${AZURE_DEVOPS_TOKEN}" ]; then
          git config --global credential."https://dev.azure.com".helper '!f() { echo "username=pat"; echo "password='"${AZURE_DEVOPS_TOKEN}"'"; }; f'
          git config --global credential."https://dev.azure.com".useHttpPath true
        fi

        # GitLab - inline credential helper
        if [ -n "${GITLAB_TOKEN}" ]; then
          git config --global credential."https://gitlab.com".helper '!f() { echo "username=oauth2"; echo "password='"${GITLAB_TOKEN}"'"; }; f'
          git config --global credential."https://gitlab.com".useHttpPath true
        fi

    - name: Install xfg
      shell: bash
      run: |
        if [ "${{ inputs.xfg-package }}" = "skip" ]; then
          echo "Skipping xfg installation (using pre-installed)"
        elif [ -n "${{ inputs.xfg-package }}" ]; then
          echo "Installing xfg from: ${{ inputs.xfg-package }}"
          npm install -g "${{ inputs.xfg-package }}"
        else
          VERSION=$(node -p "require('${{ github.action_path }}/package.json').version")
          echo "Installing xfg@${VERSION} (from action release)"
          npm install -g "@aspruyt/xfg@${VERSION}"
        fi

    - name: Run xfg
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        XFG_GITHUB_APP_ID: ${{ inputs.github-app-id }}
        XFG_GITHUB_APP_PRIVATE_KEY: ${{ inputs.github-app-private-key }}
        AZURE_DEVOPS_EXT_PAT: ${{ inputs.azure-devops-token }}
        GITLAB_TOKEN: ${{ inputs.gitlab-token }}
      run: |
        # Build command with required arguments
        CMD="xfg ${{ inputs.command }}"
        CMD="$CMD --config ${{ inputs.config }}"
        CMD="$CMD --work-dir ${{ inputs.work-dir }}"
        CMD="$CMD --retries ${{ inputs.retries }}"

        # Add optional flags (shared)
        if [ "${{ inputs.dry-run }}" = "true" ]; then
          CMD="$CMD --dry-run"
        fi

        if [ "${{ inputs.no-delete }}" = "true" ]; then
          CMD="$CMD --no-delete"
        fi

        # Add sync-only flags
        if [ "${{ inputs.command }}" = "sync" ]; then
          if [ -n "${{ inputs.branch }}" ]; then
            CMD="$CMD --branch ${{ inputs.branch }}"
          fi

          if [ -n "${{ inputs.merge }}" ]; then
            CMD="$CMD --merge ${{ inputs.merge }}"
          fi

          if [ -n "${{ inputs.merge-strategy }}" ]; then
            CMD="$CMD --merge-strategy ${{ inputs.merge-strategy }}"
          fi

          if [ "${{ inputs.delete-branch }}" = "true" ]; then
            CMD="$CMD --delete-branch"
          fi
        fi

        # Execute
        echo "Running: $CMD"
        eval "$CMD"
