coverage:
  status:
    project:
      default:
        target: 95%
        threshold: 1%
        base: auto
    patch:
      default:
        target: 95%
        threshold: 1%

ignore:
  # Interface-only files with no executable code
  - "src/strategies/commit-strategy.ts"

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
