coverage:
  status:
    project:
      default:
        target: 95%
        threshold: 1%
        base: auto
    patch:
      default:
        target: 95%
        threshold: 1%

ignore:
  # Entry point (just calls parse)
  - "src/cli.ts"

  # Re-export only
  - "src/index.ts"

  # CLI configuration (declarative, tested via integration)
  - "src/cli/program.ts"

  # Type-only files (no executable code)
  - "src/cli/types.ts"
  - "src/config/types.ts"
  - "src/sync/types.ts"
  - "src/vcs/types.ts"
  - "src/settings/rulesets/types.ts"
  - "src/settings/repo-settings/types.ts"

  # Re-export index files (no logic, just exports)
  - "src/cli/index.ts"
  - "src/config/index.ts"
  - "src/sync/index.ts"
  - "src/vcs/index.ts"
  - "src/shared/index.ts"
  - "src/output/index.ts"
  - "src/settings/index.ts"
  - "src/settings/rulesets/index.ts"
  - "src/settings/repo-settings/index.ts"

  # Test utilities
  - "test/mocks/**"

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
