coverage:
  status:
    project:
      default:
        target: 95%
        threshold: 1%
        base: auto
    patch:
      default:
        target: 95%
        threshold: 1%

ignore:
  # Types
  - "src/cli/types.ts"
  - "src/config/types.ts"
  - "src/sync/types.ts"
  # Interface-only files with no executable code
  - "src/strategies/commit-strategy.ts"
  - "src/strategies/ruleset-strategy.ts"
  # Test utilities (mock implementations for testing, not production code)
  - "test/mocks/**"

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
